EXEC_NAME := heat
SOURCES := input_data.F90 RHS_fun.F90 main.F90
PROBLEM_MODULES := input_data rhs_fun
DEFAULT_ARGS := 2 1 1 0.01 1 1 1
USAGE := <size> <order> <steps> <dt> <procx> <procy> <procz>

include ../problem.mk
