EXEC_NAME := l2
SOURCES := input_data.F90 RHS_fun.F90 main.F90
PROBLEM_MODULES := input_data rhs_fun
DEFAULT_ARGS := 2 2 2 1 1 1 1
USAGE := <isizex> <isizey> <isizez> <order> <procx> <procy> <procz>

include ../problem.mk
