!------------------------------------------------------------------------------
!
! MODULE: plot
!
! DESCRIPTION:
!> @file plot.F90
!> @brief Module providing sampling and export wrappers for scalar
!> functions and spline fields.
!>
!> @details
!> This module defines:
!> - the plotting-parameter container \ref PlotParams,
!> - a generic sampling routine for scalar functions through
!>   \ref SavePlot,
!> - a spline-field sampling routine through \ref SaveSplinePlot.
!>
!> The module acts as a thin orchestration layer between:
!> - evaluation of scalar functions or spline fields,
!> - generation of structured sampling grids from user-defined ranges and
!>   resolutions,
!> - backend-specific output procedures such as \ref GnuPlotOutput or
!>   \ref VtkOutput.
!>
!> The sampled values are always stored on a structured three-dimensional
!> grid described by \ref PlotParams and then passed to an output
!> callback supplied by the caller.
!
!------------------------------------------------------------------------------
module plot

   implicit none

!---------------------------------------------------------------------------
!
! DESCRIPTION:
!> @brief Container describing the spatial extent and resolution of a
!> structured sampling grid.
!>
!> @details
!> This derived type stores:
!> - the lower and upper bounds of the sampling interval in each
!>   coordinate direction,
!> - the number of sampling points in each direction.
!>
!> It is used by plotting and export routines to define a tensor-product
!> grid on which scalar functions or spline fields are evaluated prior to
!> serialization.
!
! Notes:
! ------
!> @note
!> The stored coordinate bounds are interpreted as inclusive endpoints of
!> the sampling interval in each direction.
!
!---------------------------------------------------------------------------
   type PlotParams
!> @brief Lower and upper sampling bounds in the first direction.
      real(kind=8) :: startx, endx
!> @brief Lower and upper sampling bounds in the second direction.
      real(kind=8) :: starty, endy
!> @brief Lower and upper sampling bounds in the third direction.
      real(kind=8) :: startz, endz

!> @brief Numbers of sampling points in the three coordinate directions.
      integer(kind=4) :: resx, resy, resz
   end type PlotParams

contains

!---------------------------------------------------------------------------
!
! DESCRIPTION:
!> @brief Samples a scalar function on a structured grid and forwards the
!> resulting values to an output backend.
!>
!> @details
!> This routine evaluates the scalar function \p f on the tensor-product
!> grid defined by \p params. In each coordinate direction, the grid
!> points are generated by linear interpolation between the corresponding
!> interval bounds using \ref lerp from module `math`.
!>
!> The routine:
!> - constructs sampling coordinates in the first, second, and third
!>   directions,
!> - evaluates the function \p f at every grid point,
!> - stores the sampled values in the array \p vals,
!> - passes the resulting array to the user-supplied output procedure
!>   \p output.
!>
!> This routine is backend-agnostic. The actual serialization format is
!> determined entirely by the supplied output callback.
!
! Input:
! ------
!> @param[in] filename
!> Base filename or filename pattern passed to the output backend.
!>
!> @param[in] f
!> Scalar function to be sampled on the structured grid.
!>
!> @param[in] output
!> Output callback responsible for serializing the sampled values.
!>
!> @param[in] params
!> Plot-parameter structure defining coordinate ranges and grid
!> resolutions.
!
! Notes:
! ------
!> @note
!> The routine assumes at least two sampling points in each direction
!> when constructing interpolation parameters of the form
!> \f$(i-1)/(N-1)\f$.
!
!> @warning
!> If any resolution in \p params is equal to one, the interpolation
!> formula introduces a division by zero.
!
!---------------------------------------------------------------------------
subroutine SavePlot(filename, f, output, params)
   use math, ONLY: lerp
   implicit none
   interface
      function f(x, y, z) result(val)
         real(kind=8) :: x, y, z, val
      end function

      subroutine output(filename, vals, params)
         import PlotParams
         character(len=*), intent(in) :: filename
         type(PlotParams), intent(in) :: params
         real(kind=8), intent(in) :: vals(params%resx, params%resy, params%resz)
      end subroutine
   end interface

!> @brief Base filename or filename pattern passed to the output backend.
   character(len=*), intent(in) :: filename
!> @brief Plot parameters defining the sampling grid.
   type(PlotParams) :: params
!> @brief Sampled scalar values on the structured grid.
   real(kind=8) :: vals(params%resx, params%resy, params%resz)
!> @brief Loop counters over the three coordinate directions.
   integer(kind=4) :: ix, iy, iz
!> @brief Physical coordinates and normalized interpolation parameter.
   real(kind=8) :: x, y, z, t

   ! Compute function values
   do ix = 1, params%resx
      t = (ix - 1)/dble(params%resx - 1)
      x = lerp(t, params%startx, params%endx)
      do iy = 1, params%resy
         t = (iy - 1)/dble(params%resy - 1)
         y = lerp(t, params%starty, params%endy)
         do iz = 1, params%resz
            t = (iz - 1)/dble(params%resz - 1)
            z = lerp(t, params%startz, params%endz)
            vals(ix, iy, iz) = f(x, y, z)
         end do
      end do
   end do

   call output(filename, vals, params)

end subroutine SavePlot

!---------------------------------------------------------------------------
!
! DESCRIPTION:
!> @brief Samples a tensor-product spline field on a structured grid and
!> forwards the resulting values to an output backend.
!>
!> @details
!> This routine evaluates a three-dimensional spline field defined by the
!> knot vectors \p Ux, \p Uy, \p Uz, polynomial degrees \p px, \p py,
!> \p pz, basis sizes \p nx, \p ny, \p nz, element counts \p nelemx,
!> \p nelemy, \p nelemz, and coefficient tensor \p coeffs.
!>
!> The sampling grid is generated from \p params in the same manner as in
!> \ref SavePlot, namely by linear interpolation between the prescribed
!> coordinate bounds. At each sampled point, the spline value is obtained
!> through \ref EvalSpline from module `basis`.
!>
!> The routine:
!> - constructs the sampling coordinates in each direction,
!> - evaluates the spline field at all grid points,
!> - stores the resulting scalar field in \p vals,
!> - passes the sampled field to the user-supplied output procedure
!>   \p output.
!
! Input:
! ------
!> @param[in] filename
!> Base filename or filename pattern passed to the output backend.
!>
!> @param[in] Ux
!> Knot vector in the first parametric direction.
!>
!> @param[in] px
!> Polynomial degree in the first direction.
!>
!> @param[in] nx
!> Number of basis functions minus one in the first direction.
!>
!> @param[in] nelemx
!> Number of elements in the first direction.
!>
!> @param[in] Uy
!> Knot vector in the second parametric direction.
!>
!> @param[in] py
!> Polynomial degree in the second direction.
!>
!> @param[in] ny
!> Number of basis functions minus one in the second direction.
!>
!> @param[in] nelemy
!> Number of elements in the second direction.
!>
!> @param[in] Uz
!> Knot vector in the third parametric direction.
!>
!> @param[in] pz
!> Polynomial degree in the third direction.
!>
!> @param[in] nz
!> Number of basis functions minus one in the third direction.
!>
!> @param[in] nelemz
!> Number of elements in the third direction.
!>
!> @param[in] coeffs
!> Tensor-product coefficient array of the spline field.
!>
!> @param[in] output
!> Output callback responsible for serializing the sampled values.
!>
!> @param[in] params
!> Plot-parameter structure defining coordinate ranges and grid
!> resolutions.
!
! Notes:
! ------
!> @note
!> The current implementation samples the spline value itself by calling
!> `EvalSpline` with derivative order equal to zero.
!
!> @warning
!> As in \ref SavePlot, any unit resolution in \p params leads to a
!> division by zero in the interpolation parameter.
!
!---------------------------------------------------------------------------
subroutine SaveSplinePlot(filename, &
                           Ux, px, nx, nelemx, &
                           Uy, py, ny, nelemy, &
                           Uz, pz, nz, nelemz, &
                           coeffs, output, params)
   use math, ONLY: lerp
   use basis, ONLY: EvalSpline
   interface
      subroutine output(filename, vals, params)
         import PlotParams
         character(len=*), intent(in) :: filename
         type(PlotParams), intent(in) :: params
         real(kind=8), intent(in) :: vals(params%resx, params%resy, params%resz)
      end subroutine
   end interface

!> @brief Base filename or filename pattern passed to the output backend.
   character(len=*), intent(in) :: filename
!> @brief Basis size minus one, degree, and element count in the first direction.
   integer(kind=4), intent(in) :: nx, px, nelemx
!> @brief Basis size minus one, degree, and element count in the second direction.
   integer(kind=4), intent(in) :: ny, py, nelemy
!> @brief Basis size minus one, degree, and element count in the third direction.
   integer(kind=4), intent(in) :: nz, pz, nelemz
!> @brief Knot vector in the first direction.
   real(kind=8), intent(in) :: Ux(0:nx + px + 1)
!> @brief Knot vector in the second direction.
   real(kind=8), intent(in) :: Uy(0:ny + py + 1)
!> @brief Knot vector in the third direction.
   real(kind=8), intent(in) :: Uz(0:nz + pz + 1)
!> @brief Tensor-product spline coefficients.
   real(kind=8), intent(in) :: coeffs(0:nx, 0:ny, 0:nz)
!> @brief Plot parameters defining the sampling grid.
   type(PlotParams) :: params
!> @brief Sampled spline values on the structured grid.
   real(kind=8) :: vals(params%resx, params%resy, params%resz)
!> @brief Physical coordinates and normalized interpolation parameter.
   real(kind=8) :: x, y, z, t
!> @brief Loop counters over the three coordinate directions.
   integer(kind=4) :: ix, iy, iz

   ! Compute function values
   do ix = 1, params%resx
      t = (ix - 1)/dble(params%resx - 1)
      x = lerp(t, params%startx, params%endx)
      do iy = 1, params%resy
         t = (iy - 1)/dble(params%resy - 1)
         y = lerp(t, params%starty, params%endy)
         do iz = 1, params%resz
            t = (iz - 1)/dble(params%resz - 1)
            z = lerp(t, params%startz, params%endz)
            vals(ix, iy, iz) = EvalSpline(0, Ux, px, nx, nelemx, Uy, py, ny, nelemy, &
                                          Uz, pz, nz, nelemz, coeffs, x, y, z)
         end do
      end do
   end do

   call output(filename, vals, params)

end subroutine SaveSplinePlot

end module plot
